platform :ios do 
    desc "Bundle Release for the ios beta"
    lane :beta do
        update_code_signing_settings(use_automatic_signing: true, path: "AwesomeProject.xcodeproj", team_id: "2PC94S32ZB", bundle_identifier: "com.awesomeproject.2PC94S32ZB", profile_name: "Håkan Lundblad (Personal Team)")
        gym(project: "AwesomeProject.xcodeproj")
    end
end