platform :ios do 
    desc "Bundle Release for the ios beta"
    lane :beta do
        enable_automatic_code_signing(path: "AwesomeProject.xcodeproj")
        gym(project: "AwesomeProject.xcodeproj", skip_profile_detection: true)
    end
end