platform :android do 
    desc "Release for the Android beta"
    lane :beta do
        gradle(task: 'clean', project_dir: './')
        gradle(task: 'bundle', build_type: 'Release', project_dir: './')
        supply(track: 'beta', abb: './app/build/outputs/apk/app-beta-release.apk')
    end
end