# This is a basic workflow to help you get started with Actions

name: IOS Production Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ios-build:
    name: IOS Production Build
    runs-on: macOS-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install npm dependencies
        run: yarn
        
      - name: Ruby version
        run: ruby --version

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: cd ios && pod install --repo-update && cd ..
        
      - name: Xcode Version
        run: /usr/bin/xcodebuild -version
        
      - name: React Native run-ios
        run: cd ios && xcodebuild clean archive -scheme AwesomeProject -workspace AwesomeProject.xcworkspace -configuration Release -archivePath ./builds/AwesomeProject.xcarchive -destination id=FF9C5FDC-127D-4A5C-A660-9EBD6D8A01D7 && cd ..
        
      - name: List folder
        run: cd ios && ls -R ./build/
