# This is a basic workflow to help you get started with Actions

name: Build Android

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
        - '2.7'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install npm dependencies
        run: yarn
        
      - name: Setup Fastlane
        working-directory: ./
        run: | 
          bundle install
          bundle update fastlane
          
      - name: Build and upload to TestFlight
        working-directory: ./android
        run: |
          bundle exec fastlane android beta
        
      - name: List folder
        run: ls -R ./

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release
      #     path: android/app/build/outputs/apk/release/app-release.aab
          
      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: release
          
      # - name: upload artifact to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
      #     token: ${{secrets.FIREBASE_TOKEN}}
      #     groups: Android1
      #     file: app-release.aab
