# This is a basic workflow to help you get started with Actions

name: IOS Production Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ios-build:
    name: IOS Production Build
    runs-on: macOS-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install npm dependencies
        run: yarn
        
      - name: Ruby version
        run: ruby --version

      - name: Setup Fastlane
        working-directory: ./
        run: | 
          bundle install
          bundle update fastlane

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: cd ios && pod install --repo-update && cd ..

      # - name: Init Fastlane match
      #   run: cd ios && fastlane match init && cd ..

      - name: Fastlane match development
        run: cd ios && fastlane match development --app_identifier "org.yahiro.AwesomeProject" --verbose && cd ..        

      - name: Build bundle with Fastlane
        run: |
          cd ios && bundle exec fastlane ios beta --verbose && cd ..

      # - name: Xcode Version
      #   run: /usr/bin/xcodebuild -version
        
      # - name: Xcodebuild build archive
      #   run: cd ios && xcodebuild clean archive -scheme AwesomeProject -sdk iphoneos -workspace AwesomeProject.xcworkspace -configuration Release -archivePath ./build/AwesomeProject.xcarchive build CODE_SIGNING_ALLOWED=NO && cd ..
        
      - name: List folder
        run: cd ios && ls -R ./build/
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ios/build/AwesomeProject.xcarchive/Products/Applications/AwesomeProject.app
